title: Prachtsaal Studio
email: info@prachtsaal.berlin
description: >- # this means to ignore newlines until "baseurl:"
  Neuk√∂lln's non-profit art cooperative.
url: "https://prachtsaal.berlin" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  people:
    sort_by: full_name
    # output: true  # uncomment if want member pages

future: true

# plugins:
#   - jekyll-sitemap
#   - jekyll-seo-tag 
#   - jekyll-feed
